# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrudRealm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CrudRealm

 #pod 'RealmSwift'
 pod 'RealmSwift', '~> 3.20.0'
  target 'CrudRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrudRealmUITests' do
    # Pods for testing
  end

end
